<?php

/**
 * PluginEventLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEventLogTable extends Doctrine_Table
{
  /**
   * Retrieves all associated log entries for the given model
   *
   * @param $model the model for which event logs are being retrieved
   * @param DateTime $from only get events logged after this date/time
   * @param DateTime $to only get events logged before this date/time
   *
   * @return Doctrine_Collection
   */
  public function getEventLogsForModel($model, $from = null, $to = null)
  {
    $q = Doctrine_Query::create()
      ->from('EventLog')
      ->where('object_model = ?', $model)
      ->orderBy('created_at DESC');
    
    if($from)
    {
      if(!($from instanceof DateTime))
      {
        throw new sfException('"From" passed to getEventLogsForModel must be an instance of DateTime');
      }
      
      $q->andWhere('created_at >= ?', $from->format('Y-m-d H:i:s'));
    }
    
    if($to)
    {
      if(!($to instanceof DateTime))
      {
        throw new sfException('"To" passed to getEventLogsForModel must be an instance of DateTime');
      }
      
      $q->andWhere('created_at <= ?', $to->format('Y-m-d H:i:s'));
    }
    
    return $q->execute();
  }
}