<?php

/**
 * PluginEventLogNoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginEventLogNoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginEventLogNoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginEventLogNote');
    }
}