<?php

/**
 * PluginEventLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginEventLog extends BaseEventLog
{
  /**
   * @return the object affected by the logged event
   */
  public function getObject()
  {
    return Doctrine_Core::getTable($this->object_model)->find($this->object_id);
  }
}